FROM n8nio/n8n

# Создаём директорию для данных
RUN mkdir -p /data

# Копируем базу данных в контейнер
COPY database.sqlite /data/database.sqlite

# Устанавливаем права доступа
RUN chown -R node:node /data

# Указываем рабочую директорию
WORKDIR /home/node

# Запускаем n8n
USER node
CMD ["n8n"]